-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.departments
(
    dept_no character varying(5) NOT NULL,
    dept_name character varying(20) NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (dept_no)
);

COMMENT ON TABLE public.departments
    IS 'Department Master Data';
END;